version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 100
      runas: root
      overwrite: true
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root
      overwrite: true
