services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
